apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    name: queue
    release: "1"
    
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  
